# Generated by Django 3.1.4 on 2020-12-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('part', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.contestparticipant')),
                ('prob', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
    ]
